version: '3'

services:
  web:
    restart: always
    build: 
      context: install/webserver
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    links: 
      - db:db
    ports:
      - 5001:5001
    environment:
      - DATABASE_URI=postgresql://dev:dev@db:5432/cross_product
      - PORT=5001
    command:  gunicorn --bind 0.0.0.0:5001 app:app

  proxy:
    image: nginx:1.13-alpine
    volumes: 
      - ./install/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/usr/src/app
    depends_on:
      - web
    ports:
      - 8003:8003

  db: 
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=cross_product
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

volumes: 
  postgres: {}
    

